"""QRcode model

Revision ID: 7652d35d3142
Revises: 7e3846062943
Create Date: 2022-12-22 23:12:35.990958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7652d35d3142'
down_revision = '7e3846062943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_codes')
    # ### end Alembic commands ###
